### PR TITLE
Fix sonar issues

### PR DESCRIPTION
**Pull request by brrritssocold**
Fix various code issues introduced in the last days. Attempts to reduce code rot.

### CODE REVIEW

**Comment by Stadler76** [comment]
@brrritssocold could you explain to me, why you're using strict comparisons? I can't see any benefit to it. 

And AFAICS strict comparisons in AS3 is kinda borked:
```as3
var temp:Number = 0;
trace('temp === 0:', temp === 0);
trace('temp === 0.0:', temp === 0.0);
```
Both eval to true.

**Comment by Kitteh6660** [comment]
Congratulations on being the one to create a 1000th pull request!

**Comment by Stadler76** [comment]
@Kitteh6660 wrote:
> Congratulations on being the one to create a 1000th pull request!

Dammit ... 18 Minute too slow :-/

Well, congrats from me, too.

**Comment by brrritssocold** [comment]
❗️ 

Didn't notice. Thanks!

**Pull request merged**
