### PR TITLE
Inventory Deletion Toggle

### PR DESCRIPTION
**Pull request by Foxwells**
Instead of holding shift, there's now a toggle button. That way people won't get shift-stuck like [https://github.com/Kitteh6660/Corruption-of-Champions-Mod/issues/418](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/issues/418).

Switches between deleting one at a time, all in a stack, and not deleting. Not deleting is the default, ofc.

### CODE REVIEW

**Comment by Kitteh6660** [comment]
I would recommend making the toggle button noticable.

0 = Trash Items: Off
1 = Trash Items: 1x
2 = Trash Items: All

**Comment by Foxwells** [comment]
You mean, change the button names?

**Comment by Kitteh6660** [comment]
Yes.

**Comment by Foxwells** [comment]
That good?

**Comment by Kitteh6660** [comment]
I'll rename the buttons myself after that, thanks.

**Pull request merged**
