### PR TITLE
Salamander firewater

### PR DESCRIPTION
**Pull request by Ormael**
I didn't include desp parts for each new body part since...I can't find file for desc appearance of PC on your mod now so please tell me what path is for it so I can add this missing parts. Other than that and few cut out parts of features that your mod not support anyway rest of code I added in this pull request.

Cheers

(oh and if you aside needed adjustments keep code intact not change name of TF unless you made enough changes to itself to justify name change, ok?)

### CODE REVIEW

**Comment by Kitteh6660** [comment]
Have you tested the code to make sure it works?

**Comment by Ormael** [comment]
In my mod code working perfecty fine. You can ask anyone in my mod thread if they got any issues with it. I think you might look into this code to be sure it's fitting for your current code base as all that was made with using 1.3.8 or 1.3.9 revamp mod version code. If you made any huge changes to code since then you will need look if somewhere you need to adjust it to your standards.

**Comment by Ormael** [comment]
Ok now all pieces of code for salamander firewater that are supported by your mod are in PR (possibly you need look and see if somewhere my code and your code are different way written to adjust it to your current version code structure - as promised I gave you raw code for this TF item with all connected things/stuff way it was in my code ^^ )

Cheers

**Comment by Kitteh6660** [comment]
I'll accept the PR as soon as I can get back home and work on an update.

**Comment by Ormael** [comment]
Ok do what you need to make it work with revamp. And if you would like get code for something else of my mod in future just gimme a shot or dunno post about it in my mod thread/send me a PM

**Comment by Kitteh6660** [comment]
Finally merged. I'll make some tweaks. Keep in mind that sometime after 1.3.9, there were huge refactors, especially cutting down the size of includes folder a lot.

I'll keep that in mind, thanks.

**Pull request merged**
