### PR TITLE
Corruption Tolerance Consistency

### PR DESCRIPTION
**Pull request by Foxwells**
I accidentally uploaded all the files to the main folder instead of the folders they belong in so that's why there's a lot of "updated x" followed by "deleted x"

Anyway added more corruption tolerance stuff to try and give it more relevancy and consistency throughout the game. I probably overlooked something so lmk if you spot anything.

For my mang man at [https://github.com/Kitteh6660/Corruption-of-Champions-Mod/issues/460](https://github.com/Kitteh6660/Corruption-of-Champions-Mod/issues/460)

### CODE REVIEW

**Comment by Netys** [comment]
You can try to squash your commits to get rid of this mess:
http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit

**Comment by Foxwells** [comment]
I legit have no idea what the fuck any of that says but thank you for attempting to help me.

**Comment by Netys** [comment]
Yeah, git is a mindfuck. This is a way to combine all that commits into one, thus getting rid of the mistake.

**Comment by Foxwells** [comment]
I'm not sure that's something I can do on browser GitHub...

Are you in the Discord? I'll log on in a sec, can you PM me how to go about this? That page is really confusing to me z_z

**Comment by Netys** [comment]
It's not a GutHub feature; you'll have to use the command line. I guess you are using TortoiseGit now? AFAIK it can't do it this way, but you can create another branch from master and pull from your current branch with "squash" option using "browse references" to pull from a local branch.

I'm not using Discord.

**Comment by Foxwells** [comment]
I... don't know what a command line is, and I have no idea what TortoiseGit is. I just use the website. But I'll give it a try?

**Comment by Netys** [comment]
Have no idea, how to do this using web interface only. I'm using local clone to work (with TortoiseGit interface, since console git is _a bit_ too hardcore). A bit more complicated, but more flexible. Local tests are good too to know if your stuff works.

**Pull request closed without merging**
