### PR TITLE
Making panel movement instantaneous to attempt to fix imagepack bug

### PR DESCRIPTION
**Pull request by BelshazzarII**

### CODE REVIEW

**Comment by Fergusson951** [comment]
will be like this or...

**Comment by brrritssocold** [comment]
The release build hanged and needs to be restarted.

**Comment by Stadler76** [comment]
Simply fix the warnings and Travis would rerun anyway

**Comment by Fergusson951** [comment]
probably duplicates

**Comment by Fergusson951** [comment]
wasn't in first version

**Pull request closed without merging**
