### PR TITLE
Pic Date 4 Rathazul

### PR DESCRIPTION
**Pull request by Fergusson951**
= 61 pic folders

### CODE REVIEW

**Comment by Kitteh6660** [comment]
The reason I closed is that it would unfix the tooltip and mix-up issues. Please re-fix it before I'll accept.

**Comment by Fergusson951** [comment]
Ok

2017-08-28 8:19 GMT+05:00 Kitteh6660 <notifications@github.com>:

**Comment by Fergusson951** [comment]
8 Ebonbloom to 10

**Comment by Fergusson951** [comment]
already = 4 fixes

**Pull request merged**
