### PR TITLE
Serialize item storage

### PR DESCRIPTION
**Pull request by brrritssocold**
Use serialization for items stored in the PC's inventory.

- `ItemSlot` is now serializable
- Moved item slots to `Inventory`
- Cleaned up `itemSlot` save / load code 
- Added some documentation to `Inventory`

### CODE REVIEW

**Comment by brrritssocold** [comment]
Hmm this is interesting, debug build runs without issues on local machines.
I will look into it.

**Comment by Stadler76** [comment]
2019-01-21 04_59_17-unit test results
This test seems to always fail. At least in the debug build.

**Comment by brrritssocold** [comment]
Yeah, I'm trying to see if I can replicate the issue with a debugger attached.
If that is not possible, adding logging code to figure out what is going on.

Been busy the past few days, so have not gotten round to it yet.

**Comment by Stadler76** [comment]
Ok, I reran the whole build just now and only the debug job fails. The release job finishes without errors. Kinda weird ...

**Comment by brrritssocold** [comment]
Update to player 31 did not help either (build-dep)

**Comment by brrritssocold** [comment]
While the Serialization Util threw an Error, it was caught and a GUI error printed. The failure was detected only during loading, because data was missing.

As to why release works, possibly a race condition with the save file or something similar (if each test uses a new save file, test+UUID in my test case, release also fails).

**Pull request merged**
