### PR TITLE
Stone mining ants + missing point for shark score

### PR DESCRIPTION
**Pull request by Ormael**
**Added**
-Option to get stones with Phylla help (plus connected to this achievement)
-Few flavor changes in description of camp depending on amount of ant children (now it depend how much we got not only if we got any of them)
-Now clearing final dungoen is rewarded with achievement too
-Clearing any dungeon also giving something now ;)
**Changes**
-Shark-morph bonus stats was unable to be attained ingame due to missing one point in sharkScore (but now it should be possible to enjoy bonuses of this type of morph)
-Fixed few typo from previous pull req

### CODE REVIEW

**Comment by Tomash667** [comment]
Are you sure about this:
`if(flags[kFLAGS.ANT_KIDS] > 1,000)`
Comma is operator not a number separator
http://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/operators.html#comma

Also there is typo "chilren"

**Comment by Ormael** [comment]
So for number here shouldn't be used any seperator just written as 1000?
As for typo I humble bow to you for kindly pointing this one to me.
Both would fix when I will not be as sleepy as I'm now (that different timezones).

**Comment by Ormael** [comment]
Fix'd incorrect flags and chilren typo. Should be fine now to be merged...I think.

**Comment by Tomash667** [comment]
Onemore typo found ::)
`"Kingdomn", kACHIEVEMENTS.POPULATION_KINGDOMN`

**Comment by Ormael** [comment]
And it's squished (along with something new I worked on in the meantime) So Tomash look over once again to see if you can see any new typo still not fixed ;)

**Pull request merged**
