### PR TITLE
Disable Perks Status Effect

### PR DESCRIPTION
**Pull request by Foxwells**
Round 2: Now with cleanliness!

> Hey have you ever just like really fuckin hated everyone and/or wanted to piss them off? Then boy do I got the thing for you: Straight up disable perks with this status effect. Nullifies their use. Or at least, combat-related ones. And some other miscellaneous ones.
>
> I've created this status effect with **dungeons** in mind. Meaning, if it wouldn't affect a dungeon, I skipped over it to save my sanity. Likewise, I also **strongly advise against using this anywhere but dungeons.** The reason that I made this for dungeons is due to the severe lack of challenge in dungeons. You become too overpowered once you have a bunch of perks. So, by applying this status effect while you're in there, you can disable those perks (among other things I'll be setting up ;3c) and make the dungeon actually difficult.
>
> Likewise, I created this with a _specific_ dungeon in mind. I've been working on one for the past several days that is meant to be very difficult, and this is one of a few things I've set up for it. I do think this could be used for future dungeons though ~~plus I don't want to dump a massive PR just for it~~ so\~ Just something to consider and have at disposal, I guess!

### CODE REVIEW

**Comment by Netys** [comment]
> You become too overpowered once you have a bunch of perks.

Err... Wut? That's the point of leveling - becoming more powerful.

**Comment by Foxwells** [comment]
@Netys 
And then the game becomes fantastically boring. This status effect is a way of temporarily setting you back without forcing you to ascend or respec your perks (which really, does NOT help since ascension is super easy and respec refunds your perk points). Use it in content dungeons so people can have challenges post-game. That's why people like set-level/stat/etc things. They're hard. You can't rely on just being a wall, you actually have to fight and think. Which, since CoC lacks any of that once you get to about level 15, is something I feel we could use.

**Comment by Kitteh6660** [comment]
Or you know, try doing level 1 run.

**Comment by Netys** [comment]
Extreme/Hardcore undefeated run is quite challenging too.

**Comment by Foxwells** [comment]
@Kitteh6660 I did. And the hardest part of that wasn't even Lethice, it was the damn Minotaur King... Man fuck that guy. Regardless, I don't see why a Level 1 run should substitute the ability to make a dungeon have upped difficulty. I am forcing literally no one to use this, but I intend to and other people may want to as well, so here it is.

@Netys With all due respect, are we even playing the same game? I play on extreme/hardcore all the time with little problem. Though I suppose I've kind of latched onto this game as my priority time-waster and have played the ins and outs very thoroughly, so.

**Comment by Netys** [comment]
Undefeated run with reluctant leveling to get more experience from all encounters is not that easy. Even if you know how to get maxed out stats safely.

**Comment by Foxwells** [comment]
I've never found any issue. And regardless: That doesn't negate having a _temporary, voluntary status effect_ available for dungeon makers who may want to put such a unique restriction in their dungeon.

**Comment by Netys** [comment]
Unless it is a game within a game like a prison, this would be a bad design choice to change set rules.

**Comment by Foxwells** [comment]
Are dungeons not mini-games within the game, considering their intense involvement with quests? And how is it a bad design choice? Are you forgetting that these rules can have logical explanations in-game and proper warnings so the player knows what they're getting into?

And again. I am forcing zero (0) people to use this. But I plan to since I've been working on a special dungeon that will require perk disabling if it's to be any sort of the challenge it's supposed to be. I have applied this to **nothing**, only coded its mere existence and **possibility** for use. Nothing existing has been changed. It's just _there._

**Pull request closed without merging**
