### PR TITLE
Converted Creature.breastRows to Vector.<BreastRowClass>

### PR DESCRIPTION
**Pull request by Stadler76**
In addition to that, due to the added strictness, I've stumble into and fixed a few bugs:
- ditch unused `breastsPerRow`
- `nippleLength` was used as a `BreastRowClass`-property, where it should be used as a `Creature`-property

**[Update:] Same thing for Creature.cocks**
Along with that I've found another small bug in ImpFood.as: `Cock.cockType` has to be of `CockTypesEnum`

### CODE REVIEW

**Comment by brrritssocold** [comment]
Wouldn't it be better to leave `nippleLength` in the `BreastRowClass` class?
Then again it can be moved in to the class if there ever is code that would work with different nipple lengths per breast row.

**Comment by Stadler76** [comment]
@brrritssocold commented:
> Wouldn't it be better to leave `nippleLength` in the `BreastRowClass` class?
> Then again it can be moved in to the class if there ever is code that would work with different nipple lengths per breast row.

If you think, that should be refactored, then feel free.
Running `grep -P --color=auto -rn "\w+\.nippleLength" .` on the commandline or shell accordingly shows, that it is being used quite intensively in the codebase.

If you want to refactor this and move it to the BreastRowClass, I'd suggest the following steps in prep for this:
1. Rewrite Creature.nippleLength to a setter, that sets the nippleLength to the same value for all breast rows.
2. The getter for `Creature.nippleLength` should either get the average `nippleLength` or the `nippleLength` of the first breast row (I'd presonally prefer this) or the default value, if no breast rows present.

PS: Just BTDT for `Creature.cocks` too. Didn't want to create a separate branch+PR for that.

**Comment by brrritssocold** [comment]
Looked at the breast row changes again, you are right.
Ugh. ActionScript is way too lenient, even in strict mode.

**Comment by brrritssocold** [comment]
FYI, ag (the silver searcher) is a nice alternative to grep. Note that on windows you will probably have to run it with powershell, as it does not get along too well with git-bash.

**Pull request merged**
