### PR TITLE
Remove MainView.swc

### PR DESCRIPTION
**Pull request by jfmherokiller**
This pull request completely removes the need for MainView.swc and replaces what it provided with open source components stored here https://github.com/minimalcomps/minimalcomps . 

The reason why is multiple commits is so that you can explictly see what was changed both in the files which were added and those which i had to edit in order to remove the dependency on MainView.swc .

It is also multiple commits because i was unable to reasonably separate it into smaller pull requests.

### CODE REVIEW

**Comment by Stadler76** [comment]
mmh, the scrollbar in the main textbox is missing and the background in the options-screen is white.

**Comment by Stadler76** [comment]
@jfmherokiller have you seen, that I've requested changes?

**Comment by jfmherokiller** [comment]
sorry life got in the way ill look into fixing those issues now

**Comment by jfmherokiller** [comment]
@Stadler76 i fixed the background it turns out that i forgot to set a background lol

**Comment by Stadler76** [comment]
The scrollbar is still borked:
1. its smaller
2. it doesn't scroll

**Comment by Stadler76** [comment]
The scrollbar is still borked:
1. its smaller
2. it doesn't scroll

**Comment by jfmherokiller** [comment]
@Stadler76 i fixed the scrollbar and made it scroll but i dont believe im able to directly copy the look of the original.

**Comment by Stadler76** [comment]
Almost there 👍 

But I still can't drag the bar.

**Comment by jfmherokiller** [comment]
@Stadler76 thanks for that point 👍 also sorry if the scrollbar is not directly the same as the original I kind of like it inside the textbox. Also what window cant you scroll the scrollbar in? because ive been testing the player settings and the credits page and both seem to work.

**Comment by jfmherokiller** [comment]
@Stadler76 it is now fixed go ahead and test it before merging it into master but as far as my test have shown the only issue is that the scrollbar will keep existing on the mainmenu if you open achivements or credits.

**Comment by Stadler76** [comment]
I think I could workaround the final issue.

\~approving\~

PS: Merging PRs is for @Kitteh6660 to decide.

**Comment by jfmherokiller** [comment]
btw @Stadler76 i do not know if this will actually fix the screen reader issue but it should allow us much finer control over the UI in general. since we can now directly edit the controls instead of say relying on something pre built and possibly hard to edit if possible

**Pull request merged**
